export const listings = [
  { 
    id: 1, 
    price: 185000, 
    beds: 3, 
    baths: 2, 
    sqft: 2100, 
    address: "Al Mansour District", 
    city: "Baghdad, Iraq", 
    image: "/a1.jpg", 
    status: "New Listing", 
    type: "House for sale",
    description: "A stunning modern family home located in the heart of Al Mansour. This property features an open-concept living area, premium Italian marble flooring, and a landscaped private garden perfect for evening gatherings.",
    amenities: ["24/7 Security", "Central Cooling", "Private Garden", "Garage", "Backup Generator"]
  },
  { 
    id: 2, 
    price: 95000, 
    beds: 2, 
    baths: 2, 
    sqft: 1450, 
    address: "100m Street Apartment", 
    city: "Erbil, Iraq", 
    image: "/a2.jpg", 
    status: "New Listing", 
    type: "Apartment for sale",
    description: "Modern urban living at its finest. This apartment offers panoramic views of the Erbil skyline, high-speed elevator access, and is walking distance from major shopping centers.",
    amenities: ["Elevator", "Gym Access", "24/7 Security", "Balcony", "Parking Slot"]
  },
  { 
    id: 3, 
    price: 420000, 
    beds: 6, 
    baths: 5, 
    sqft: 5200, 
    address: "Dream City Villa", 
    city: "Erbil, Iraq", 
    image: "/a3.jpg", 
    status: "Luxury", 
    type: "Luxury villa",
    description: "Exquisite 6-bedroom villa in the prestigious Dream City. Features a private swimming pool, smart home automation, and separate quarters for staff. Built with the highest international standards.",
    amenities: ["Swimming Pool", "Smart Home", "Maid's Room", "Gated Community", "Wine Cellar"]
  },
  { 
    id: 4, 
    price: 110000, 
    beds: 3, 
    baths: 2, 
    sqft: 1900, 
    address: "Al Ashar Area", 
    city: "Basra, Iraq", 
    image: "/a4.jpg", 
    status: "New Listing", 
    type: "House for sale",
    description: "A spacious traditional-style home in the historic Al Ashar area. High ceilings provide natural cooling, and the large courtyard offers a peaceful retreat from the city hustle.",
    amenities: ["Large Courtyard", "Storage Room", "Water Filtration", "Close to Market"]
  },
  { 
    id: 5, 
    price: 78000, 
    beds: 2, 
    baths: 1, 
    sqft: 1250, 
    address: "University District", 
    city: "Najaf, Iraq", 
    image: "/a5.jpg", 
    status: "Reduced", 
    type: "Apartment for sale",
    description: "Great investment opportunity or perfect for a small family. Located near major educational institutions with excellent rental yield potential.",
    amenities: ["High-speed Internet", "Security Cameras", "Furnished Kitchen", "Fire Alarm"]
  },
  { 
    id: 6, 
    price: 260000, 
    beds: 5, 
    baths: 4, 
    sqft: 4100, 
    address: "Al Jadriya", 
    city: "Baghdad, Iraq", 
    image: "/a11.jpg", 
    status: "Hot Deal", 
    type: "Villa for sale",
    description: "Exclusive villa in the upscale Al Jadriya district. This property boasts large windows for natural light, a modern kitchen island, and proximity to the Tigris river.",
    amenities: ["River View", "Roof Terrace", "Modern Kitchen", "Security Fence", "Solar Panels"]
  },
  { 
    id: 7, 
    price: 135000, 
    beds: 3, 
    baths: 2, 
    sqft: 2300, 
    address: "New Sulaymaniyah", 
    city: "Sulaymaniyah, Iraq", 
    image: "/a7.jpg", 
    status: "New Listing", 
    type: "House for sale",
    description: "A beautiful home located in the cooler hills of New Sulaymaniyah. Features central heating for winter months and a balcony with stunning mountain views.",
    amenities: ["Mountain View", "Central Heating", "Built-in Wardrobes", "Private Entrance"]
  },
  { 
    id: 8, 
    price: 89000, 
    beds: 2, 
    baths: 2, 
    sqft: 1500, 
    address: "Al Zubair", 
    city: "Basra, Iraq", 
    image: "/a8.jpg", 
    status: "New Listing", 
    type: "Apartment for sale",
    description: "Cozy and affordable apartment in a rapidly developing area. High-quality construction and modern bathroom fixtures.",
    amenities: ["Intercom System", "Laundry Room", "Basement Parking", "Street Parking"]
  },
  { 
    id: 9, 
    price: 510000, 
    beds: 7, 
    baths: 6, 
    sqft: 6000, 
    address: "Royal City Compound", 
    city: "Erbil, Iraq", 
    image: "/a9.jpg", 
    status: "Premium", 
    type: "Premium villa",
    description: "The crown jewel of Royal City. This massive 7-bedroom mansion features a private cinema, a professional-grade gym, and world-class interior design by international architects.",
    amenities: ["Private Cinema", "Home Gym", "Sauna", "Underfloor Heating", "EV Charging Station"]
  },
];