export const properties = [
  {
    id: 1,
    image: "/sold1.jpg",
    status: "Sold - Dec 13, 2025",
    price: 180000,
    beds: 3,
    baths: 2,
    sqft: "1,200",
    acres: null,
    address: "Al-Mansour District",
    city: "Baghdad, Iraq",
    type: "Single-Family Home",
  },
  {
    id: 2,
    image: "/sold2.jpg",
    status: "Sold - Dec 13, 2025",
    price: 240000,
    beds: 4,
    baths: 3,
    sqft: "1,650",
    acres: "0.3",
    address: "Dream City",
    city: "Erbil, Kurdistan Region",
    type: "Single-Family Home",
  },
  {
    id: 3,
    image: "/sold3.jpg",
    status: "Sold - Dec 12, 2025",
    price: 135000,
    beds: 2,
    baths: 1,
    sqft: "980",
    acres: null,
    address: "Al-Jadriya",
    city: "Baghdad, Iraq",
    type: "Condo",
  },
  {
    id: 4,
    image: "/sold1.jpg",
    status: "Sold - Dec 14, 2025",
    price: 320000,
    beds: 5,
    baths: 4,
    sqft: "2,300",
    acres: "0.6",
    address: "Italian Village",
    city: "Erbil, Kurdistan Region",
    type: "Single-Family Home",
  },
  {
    id: 5,
    image: "/sold2.jpg",
    status: "Sold - Dec 14, 2025",
    price: 155000,
    beds: 3,
    baths: 2,
    sqft: "1,300",
    acres: "0.25",
    address: "Al-Ashar",
    city: "Basra, Iraq",
    type: "Townhouse",
  },
  {
    id: 6,
    image: "/sold3.jpg",
    status: "Sold - Dec 11, 2025",
    price: 110000,
    beds: 2,
    baths: 1,
    sqft: "900",
    acres: null,
    address: "Al-Zahraa",
    city: "Najaf, Iraq",
    type: "Condo",
  },
  {
    id: 7,
    image: "/sold1.jpg",
    status: "Sold - Dec 10, 2025",
    price: 210000,
    beds: 4,
    baths: 3,
    sqft: "1,800",
    acres: "0.4",
    address: "Al-Karama",
    city: "Mosul, Iraq",
    type: "Single-Family Home",
  },
  {
    id: 8,
    image: "/sold2.jpg",
    status: "Sold - Dec 09, 2025",
    price: 260000,
    beds: 4,
    baths: 3,
    sqft: "1,950",
    acres: "0.5",
    address: "Royal City",
    city: "Erbil, Kurdistan Region",
    type: "Single-Family Home",
  },
  {
    id: 9,
    image: "/sold3.jpg",
    status: "Sold - Dec 08, 2025",
    price: 145000,
    beds: 3,
    baths: 2,
    sqft: "1,250",
    acres: "0.3",
    address: "Al-Harithiya",
    city: "Baghdad, Iraq",
    type: "Townhouse",
  },
  {
    id: 10,
    image: "/sold1.jpg",
    status: "Sold - Dec 07, 2025",
    price: 295000,
    beds: 5,
    baths: 4,
    sqft: "2,400",
    acres: "0.7",
    address: "English Village",
    city: "Erbil, Kurdistan Region",
    type: "Single-Family Home",
  },
  {
    id: 11,
    image: "/sold1.jpg",
    status: "Sold - Dec 07, 2025",
    price: 120000,
    beds: 2,
    baths: 1,
    sqft: "980",
    acres: null,
    address: "Al-Salam District",
    city: "Najaf, Iraq",
    type: "Condo",
  },
  {
    id: 12,
    image: "/sold2.jpg",
    status: "Sold - Dec 06, 2025",
    price: 310000,
    beds: 4,
    baths: 3,
    sqft: "2,200",
    acres: "0.6",
    address: "Royal City Compound",
    city: "Erbil, Kurdistan Region",
    type: "Single-Family Home",
  },
  {
    id: 13,
    image: "/sold3.jpg",
    status: "Sold - Dec 05, 2025",
    price: 185000,
    beds: 3,
    baths: 2,
    sqft: "1,450",
    acres: "0.4",
    address: "Al-Majmooa Al-Thaqafiya",
    city: "Baghdad, Iraq",
    type: "Townhouse",
  },
  {
    id: 14,
    image: "/sold1.jpg",
    status: "Sold - Dec 04, 2025",
    price: 275000,
    beds: 4,
    baths: 3,
    sqft: "1,850",
    acres: "0.5",
    address: "Italian Village",
    city: "Erbil, Kurdistan Region",
    type: "Single-Family Home",
  },
  {
    id: 15,
    image: "/sold2.jpg",
    status: "Sold - Dec 03, 2025",
    price: 140000,
    beds: 2,
    baths: 1,
    sqft: "1,000",
    acres: "0.3",
    address: "Al-Ashar",
    city: "Basra, Iraq",
    type: "Condo",
  },
  {
    id: 16,
    image: "/sold3.jpg",
    status: "Sold - Dec 02, 2025",
    price: 360000,
    beds: 5,
    baths: 4,
    sqft: "2,500",
    acres: "0.8",
    address: "English Village",
    city: "Erbil, Kurdistan Region",
    type: "Single-Family Home",
  },
  {
    id: 17,
    image: "/sold2.jpg",
    status: "Sold - Dec 01, 2025",
    price: 195000,
    beds: 3,
    baths: 2,
    sqft: "1,350",
    acres: "0.4",
    address: "Al-Karama",
    city: "Mosul, Iraq",
    type: "Townhouse",
  },
  {
    id: 18,
    image: "/sold1.jpg",
    status: "Sold - Nov 30, 2025",
    price: 325000,
    beds: 4,
    baths: 3,
    sqft: "2,100",
    acres: "0.6",
    address: "Al-Yarmouk",
    city: "Baghdad, Iraq",
    type: "Single-Family Home",
  },
];
