export const CategoriesDATA= [
  {
    id: 1,
    title: "Price Dropped Apartment in New York",
    price: "$780,000",
    image: "/p1.jpg",
    description: "A beautifully designed modern apartment located just minutes away from Times Square. Recently reduced in price, this unit offers spacious living, updated interiors, and breathtaking city views — perfect for urban professionals or small families.",
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    location: "New York, USA",
  },
  {
    id: 2,
    title: "Los Angeles Villa – Reduced Price",
    price: "$1,950,000",
    image: "/p2.jpg",
    description: "A luxury villa in a prime Los Angeles neighborhood, now available at an attractive discounted price. Featuring a private swimming pool, open-plan living, and premium finishes, this home is ideal for those seeking comfort, elegance, and exclusivity.",
    bedrooms: 5,
    bathrooms: 4,
    area: 4500,
    location: "Los Angeles, USA",
  },
  {
    id: 3,
    title: "Chicago House Price Reduced",
    price: "$540,000",
    image: "/p3.jpg",
    description: "A warm and well-maintained family home in the heart of Chicago. With its recent price drop, this 3-bedroom property offers excellent value, spacious interiors, and a peaceful residential environment — ideal for growing families.",
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    location: "Chicago, USA",
  },
  {
    id: 4,
    title: "Miami Condo – Huge Discount",
    price: "$980,000",
    image: "/p4.jpg",
    description: "An oceanfront condo with panoramic coastal views, now offered at a special reduced rate. Enjoy modern amenities, a resort-style environment, and quick access to Miami’s top beaches and entertainment spots.",
    bedrooms: 3,
    bathrooms: 2,
    area: 1500,
    location: "Miami, USA",
  },
  {
    id: 5,
    title: "London Townhouse — Price Cut",
    price: "£610,000",
    image: "/p5.jpg",
    description: "A charming and classic townhouse situated in a prestigious London neighborhood. This property blends historical elegance with modern comforts, and the new price makes it an exceptional opportunity for city lifestyle lovers.",
    bedrooms: 4,
    bathrooms: 3,
    area: 2000,
    location: "London, UK",
  },
  {
    id: 6,
    title: "Paris Studio Discounted",
    price: "€390,000",
    image: "/p6.jpg",
    description: "A stylish studio apartment in the romantic center of Paris. Featuring elegant interior finishes and located close to iconic landmarks, this property is now priced more affordably for investors or young professionals.",
    bedrooms: 1,
    bathrooms: 1,
    area: 650,
    location: "Paris, France",
  },
  {
    id: 7,
    title: "Melbourne House Discount",
    price: "AUD 760,000",
    image: "/p7.jpg",
    description: "A contemporary 3-bedroom home in a peaceful Melbourne suburb. Thoughtfully designed with modern interiors, spacious rooms, and a cozy atmosphere — now available at a newly reduced price.",
    bedrooms: 3,
    bathrooms: 2,
    area: 1400,
    location: "Melbourne, Australia",
  },
  {
    id: 8,
    title: "Karachi House — Reduced Price",
    price: "PKR 6.5 Crore",
    image: "/p8.jpg",
    description: "A premium house located in DHA Phase 8, Karachi. This spacious residence offers luxurious living spaces, high-end fittings, and excellent privacy, now made more attractive with its recent price reduction.",
    bedrooms: 5,
    bathrooms: 4,
    area: 3500,
    location: "Karachi, Pakistan",
  },
  {
    id: 9,
    title: "Lahore Villa Price Reduced",
    price: "PKR 4.2 Crore",
    image: "/p9.jpg",
    description: "A stunning villa in Bahria Town Lahore, featuring elegant architecture, bright interiors, and a peaceful neighborhood environment. The price cut makes this an excellent value for families seeking comfort and luxury.",
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    location: "Lahore, Pakistan",
  },
  {
    id: 10,
    title: "Islamabad Apartment — Discount",
    price: "PKR 2.1 Crore",
    image: "/p10.jpg",
    description: "A modern apartment located in the prime sector G-11, Islamabad. Offering tasteful interiors, great ventilation, and convenient access to schools and commercial areas — now available at a lower price.",
    bedrooms: 3,
    bathrooms: 2,
    area: 1600,
    location: "Islamabad, Pakistan",
  },
];
