import { Geist, Geist_Mono } from "next/font/google";
import "@/app/[locale]/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Albasync",
  description: "Generated by Albasync",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // DO NOT add <html> or <body> here.
  // Just return the children wrapped in a fragment or the font variables.
  return (
    <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      {children}
    </div>
  );
}
