export interface Property {
  id: number;
  transaction: "buy" | "rent" | "sell";
  city: string;
  type: "Apartment" | "House" | "Land" | "Office";
  priceIQD: number;
  image: string;
  address: string;
}

const SearchData: Property[] = [
  {
    id: 1,
    transaction: "buy",
    city: "Erbil",
    type: "Office",
    priceIQD: 150_000_000,
    image: "/office.jpg",
    address: "Downtown Erbil",
  },
  {
    id: 2,
    transaction: "buy",
    city: "Erbil",
    type: "Apartment",
    priceIQD: 120_000_000,
    image: "/hero4.jpg",
    address: "Empire City",
  },
  {
    id: 3,
    transaction: "buy",
    city: "Baghdad",
    type: "Apartment",
    priceIQD: 90_000_000,
    image: "/hero4.jpg",
    address: "Mansour",
  },
  {
    id: 4,
    transaction: "buy",
    city: "Baghdad",
    type: "Office",
    priceIQD: 170_000_000,
    image: "/office.jpg",
    address: "Karrada",
  },
  {
    id: 5,
    transaction: "buy",
    city: "Baghdad",
    type: "House",
    priceIQD: 210_000_000,
    image: "/hero4.jpg",
    address: "Yarmouk",
  },
  {
    id: 6,
    transaction: "buy",
    city: "Najaf",
    type: "House",
    priceIQD: 180_000_000,
    image: "/hero4.jpg",
    address: "Near Imam Ali Shrine",
  },
  {
    id: 7,
    transaction: "buy",
    city: "Najaf",
    type: "Land",
    priceIQD: 250_000_000,
    image: "/hero4.jpg",
    address: "Kufa Road",
  },
  {
    id: 8,
    transaction: "buy",
    city: "Karbala",
    type: "Apartment",
    priceIQD: 75_000_000,
    image: "/hero4.jpg",
    address: "Bab Baghdad Area",
  },
  {
    id: 9,
    transaction: "buy",
    city: "Karbala",
    type: "House",
    priceIQD: 95_000_000,
    image: "/hero4.jpg",
    address: "Al-Hur District",
  },
  {
    id: 10,
    transaction: "buy",
    city: "Basra",
    type: "Land",
    priceIQD: 220_000_000,
    image: "/hero4.jpg",
    address: "Al-Ashar District",
  },
  {
    id: 11,
    transaction: "buy",
    city: "Basra",
    type: "Apartment",
    priceIQD: 140_000_000,
    image: "/hero4.jpg",
    address: "Al-Jubaila",
  },
  {
    id: 12,
    transaction: "buy",
    city: "Mosul",
    type: "House",
    priceIQD: 130_000_000,
    image: "/hero4.jpg",
    address: "Al-Zuhour Neighborhood",
  },
  {
    id: 13,
    transaction: "buy",
    city: "Kirkuk",
    type: "Office",
    priceIQD: 110_000_000,
    image: "/office.jpg",
    address: "City Center",
  },
  {
    id: 14,
    transaction: "buy",
    city: "Sulaymaniyah",
    type: "Apartment",
    priceIQD: 160_000_000,
    image: "/hero4.jpg",
    address: "Salim Street",
  },
  {
    id: 15,
    transaction: "buy",
    city: "Hilla",
    type: "House",
    priceIQD: 105_000_000,
    image: "/hero4.jpg",
    address: "Al-Firdous District",
  },
  {
    id: 16,
    transaction: "buy",
    city: "Diwaniyah",
    type: "Land",
    priceIQD: 85_000_000,
    image: "/hero4.jpg",
    address: "Industrial Area",
  },
  {
    id: 17,
    transaction: "rent",
    city: "Najaf",
    type: "Apartment",
    priceIQD: 60_000_000,
    image: "/hero4.jpg",
    address: "Near Al-Sadiq Street",
  },
  {
    id: 18,
    transaction: "rent",
    city: "Karbala",
    type: "House",
    priceIQD: 80_000_000,
    image: "/hero4.jpg",
    address: "Al-Matahen Area",
  },
  {
    id: 19,
    transaction: "buy",
    city: "Erbil",
    type: "Land",
    priceIQD: 300_000_000,
    image: "/hero4.jpg",
    address: "Gulan Street",
  },
  {
    id: 20,
    transaction: "sell",
    city: "Baghdad",
    type: "Apartment",
    priceIQD: 95_000_000,
    image: "/hero4.jpg",
    address: "Al-Rusafa District",
  },
];

export default SearchData;
